#!/usr/bin/env python
'''
Set X11 background.
'''

import os
import sys
import Image
import random
import time
import subprocess
import tempfile

def get_screen_size():
    from Xlib.display import Display
    display = Display(os.environ.get("DISPLAY",":0.0"))
    root = display.screen().root
    w = root.get_geometry().width
    h = root.get_geometry().height
    return (w,h)
screen_size = get_screen_size()

def do_crop(image):
    sw,sh = screen_size
    sratio = float(sw)/float(sh)

    iw,ih = image.size
    iratio = float(iw)/float(ih)
    #print sratio,iratio

    if sratio > iratio:             # image is portrait
        crop_width = iw
        crop_height = int(iw/sratio)
        x = 0
        y = random.randint(0,ih-crop_height)
        crop = image.crop((x,y,x+crop_width,y+crop_height))
        return crop

    if sratio < iratio:         # image is landscape
        crop_width = int(ih*sratio)
        crop_height = ih
        x = random.randint(0,iw-crop_width)
        y = 0
        crop = image.crop((x,y,x+crop_width,y+crop_height))
        return crop

    return image


def shape_background(infile, outfile):
    '''
    Take infile and optimally shape it to fit the root window saving
    it to outfile.
    '''
    try:
        image  = Image.open(infile)
    except IOError,msg:
        print msg
        print 'File: "%s"' % infile
        raise

    crop = do_crop(image)
    crop.save(outfile,quality=95)
    del(crop)
    del(image)
    return

def set_background_gnome3(fname):
    cmd = ['gsettings', 'set', 'org.gnome.desktop.background',
           'picture-uri', 'file://'+fname]
    #print ' '.join(cmd)
    output = subprocess.check_call(cmd)
    #print output
    return

def set_background_lxde(fname):
    cmd = ['pcmanfm', '-w', fname, '--wallpaper-mode=stretch']
    #print ' '.join(cmd)
    output = subprocess.check_call(cmd)
    #print output
    return

def set_background(fname):
    '''
    Set the background root window with given file.
    '''
    #set_background_gnome3(fname)
    set_background_lxde(fname)


def get_file(dname):
    picdir = os.path.expandvars(dname)
    for path,subdir,files in os.walk(picdir):
        while True:
            fname = random.choice(files)
            if fname[0] != '.':
                return os.path.join(path,fname)
            continue
        continue
    return None


def cycle(dname, delay):
    '''
    Cycle through files in given directory and display them for given delay
    '''
    while True:
        infile = get_file(dname)
        orig,ext = os.path.splitext(infile)
        fp,outfile = tempfile.mkstemp(ext)
        shape_background(infile,outfile)
        set_background(outfile)
        time.sleep(delay)
        if os.path.exists(outfile):
            os.remove(outfile)
        continue
    return

if __name__ == '__main__':
    try:
        dname = sys.argv[1]
    except IndexError:
        dname = "$HOME/Desktop/backgrounds"
    cycle(dname,300)

