#!/bin/bash

set -e

sudo apt-get install automake1.11 gir1.2-gtk-2.0 libatk1.0-dev libaudiofile-dev libesd0-dev libgmp-dev libgmpxx4ldbl libgtk2.0-dev libpango1.0-dev libtool libxcomposite-dev libxcursor-dev libxi-dev libxml2-utils libxrandr-dev x11proto-composite-dev x11proto-randr-dev libgdbm-dev libffi-dev texinfo libxtst-dev

workdir="$1" ; shift
instdir="$1" ; shift

sudo=""
if [ -n $(echo $instdir | grep '/usr') ] ; then
    sudo="sudo"
fi

if [ -z "$instdir" ] ; then
    echo "usage: sawfish-build.sh /path/to/work /path/to/install"
    exit 1
fi

if [ "$(readlink /bin/sh)" = "/bin/dash" ] ; then
    echo "/bin/sh is dash, this build is probably not going to work"
    exit 1
fi

export CONFIG_SHELL=/bin/bash
PATH=$instdir/bin:$PATH
export PKG_CONFIG_PATH=$instdir/lib/pkgconfig

if [ ! -d "$workdir" ] ; then
    mkdir -p $workdir
fi
workdir="$(readlink -f $workdir)"

pushd $workdir

if [ ! -d librep ] ; then
    git clone https://github.com/SawfishWM/librep.git
fi
pushd librep
./autogen.sh --prefix=$instdir --exec-prefix=$instdir
make
$sudo make install
popd


if [ ! -d rep-gtk ] ; then
    git clone https://github.com/SawfishWM/rep-gtk.git
fi
pushd rep-gtk
./autogen.sh --prefix=$instdir --exec-prefix=$instdir
make
$sudo make install
popd

if [ ! -d sawfish ] ; then
    git clone https://github.com/SawfishWM/sawfish.git
fi
pushd sawfish
./autogen.sh --prefix=$instdir --exec-prefix=$instdir
make
$sudo make install
popd


xsessdir=$instdir/share/xsessions
if [ ! -d $xsessdir ] ; then
    $sudo mkdir $xsessdir
fi
$sudo cat <<EOF > $xsessdir/sawfish-mate.desktop
[Desktop Entry]
Name=Sawfish/Mate
Comment=Use the Sawfish window manager inside of the Mate desktop environment
Exec=/usr/bin/sawfish-mate-session
TryExec=mate-session
Type=Application
EOF
$sudo cmod 644 $xsessdir/sawfish-mate.desktop

$sudo cat <<EOF > $instdir/bin/sawfish-mate-session
export WINDOW_MANAGER="$instdir/bin/sawfish"
exec \$WINDOW_MANAGER & mate-session \$@
EOF
$sudo chmod 755 $instdir/bin/sawfish-mate-session

